version: '3.6'

volumes:
  cache_data:

  app_db_data:
  app_db_logs:

networks:
  app_be_net:
    name: "application_back-end_network"
    driver: overlay

services:
  cache:
    image: redis:6.2-alpine
    restart: always
    #ports:
    #  - '6379:6379'
    hostname: cache
    networks:
      - app_be_net
    command: redis-server --save 20 1 --loglevel warning --requirepass l3krjDJWlktj546lkjLKsfeLWksap
    volumes: 
      - cache_data:/data
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        constraints:
          - "node.hostname==pbg-002"

  app_db:
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    hostname: app_db
    networks:
      - app_be_net
    # ports:
    #     - '1433:1433'
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=rkli56734jlwkj45D6Fr23klrjl756a9kjreq
        - MSSQL_PID=Developer
        - MSSQL_DATA_DIR=/var/opt/sqlserver/sqldata
        - MSSQL_LOG_DIR=/var/opt/sqlserver/sqllog
    volumes:
        - app_db_data:/var/opt/sqlserver/sqldata
        - app_db_logs:/var/opt/sqlserver/sqllog
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        constraints:
          - "node.hostname==pbg-002"
