version: '3.6'

volumes:
  fe_db_data:
  fe_db_logs:

  zk_data_1:
  zk_data_2:
  zk_data_3:
  zk_logs_1:
  zk_logs_2:
  zk_logs_3:

networks:
  fe_net:
    name: "front-end_network"
    driver: overlay
  be_net:
    name: "back-end_network"
    driver: overlay

services:
  fedb:
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    hostname: fedb
    networks:
      - fe_net
    ports:
      - 21001:1433
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=rkli56734jlwkj45D6Fr23klrjl756a9kjreq
        - MSSQL_PID=Developer
        - MSSQL_DATA_DIR=/var/opt/sqlserver/sqldata
        - MSSQL_LOG_DIR=/var/opt/sqlserver/sqllog
    volumes:
        - fe_db_data:/var/opt/sqlserver/sqldata
        - fe_db_logs:/var/opt/sqlserver/sqllog
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"

  redis:
    image: 'redis:latest'
    ports:
      - 21002:6379
    environment:
      ALLOW_EMPTY_PASSWORD: 'no'
    command: redis-server --save 20 1 --loglevel warning --requirepass fljfiqdpWEPWEiqwdp03209rpolk
    networks:
      - fe_net
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"

  redis-ui:
    image: 'rediscommander/redis-commander:latest'
    ports:
      - 20002:8081
    environment:
      REDIS_HOST: redis
      REDIS_PASSWORD: fljfiqdpWEPWEiqwdp03209rpolk
    networks:
      - fe_net
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"

  zoo1:
    image: zookeeper
    hostname: zoo1
    networks:
      - be_net
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: "server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181"
    volumes: 
      - zk_data_1:/var/lib/zookeeper/data
      - zk_logs_1:/var/lib/zookeeper/log
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"

  zoo2:
    image: zookeeper
    hostname: zoo2
    networks:
      - be_net
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: "server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181"
    volumes: 
      - zk_data_2:/var/lib/zookeeper/data
      - zk_logs_2:/var/lib/zookeeper/log
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"

  zoo3:
    image: zookeeper
    hostname: zoo3
    networks:
      - be_net
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: "server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181"
    volumes: 
      - zk_data_3:/var/lib/zookeeper/data
      - zk_logs_3:/var/lib/zookeeper/log
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"

  zkui:
    image: qnib/plain-zkui
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      - be_net
    ports:
      - 20003:9090
    environment:
      ZKUI_ZK_SERVER: "zoo1:2181,zoo2:2181,zoo3:2181"
      ZKUI_USER: zoo_user
      ZKUI_USER_PW: oiruo34iuwolfkwfkjlewfkjewlfkjwflkvndflbmnmnscklqeiwhjlwifjrel4oiuoiuoidf23423

  # Kafka 1
  kafka01:
    image: "wurstmeister/kafka:2.12-2.4.1"
    hostname: kafka01
    networks:
      - be_net
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka01:9092,OUTSIDE://kafka01:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote.rmi.port=1099"
      JMX_PORT: 1099
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"

  # Kafka 2
  kafka02:
    image: "wurstmeister/kafka:2.12-2.4.1"
    hostname: kafka02
    networks:
      - be_net
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zoo2:2181"
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka02:9092,OUTSIDE://kafka02:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote.rmi.port=1099"
      JMX_PORT: 1099
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"

  # Kafka 3
  kafka03:
    image: "wurstmeister/kafka:2.12-2.4.1"
    hostname: kafka03
    networks:
      - be_net
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zoo3:2181"
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka03:9092,OUTSIDE://kafka03:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote.rmi.port=1099"
      JMX_PORT: 1099
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"

  kafka-ui:
    image: "sheepkiller/kafka-manager"
    hostname: kafka-ui
    ports:
      - 20004:9000
    networks:
      - be_net
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    environment:
      ZK_HOSTS: "zoo1:2181,zoo2:2181,zoo3:2181"
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
