version: '3.6'

volumes:
  grafana_data:

networks:
  analytics_fe_net:
    name: "analytics_front-end_network"
    driver: overlay

services:
  monitor_fe:
    image: grafana/grafana:7.5.7
    networks:
      analytics_fe_net:
    ports:
      - 20001:3000
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        constraints:
          - "node.hostname==pbg-002"

  admin_db:
    image: adminer
    restart: always
    networks:
      analytics_fe_net:
    ports:
      - 20000:8080
    environment:
      ADMINER_DEFAULT_DB_HOST: localhost
      ADMINER_DEFAULT_DB_NAME: my_db
      ADMINER_DESIGN: galkaev
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        constraints:
          - "node.hostname==pbg-002"