version: "3.8"
networks:
  analytics_be_net:
volumes:
  mysql_data:
  mysql_config:
services:
  mysql:
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - analytics_be_net
    # ports:
    #   - 21000:3306
    environment:
      MYSQL_DATABASE: 'my_db'
      MYSQL_USER: 'app_user'
      MYSQL_PASSWORD: 'K43tLklj2354Lk567kjlkwer3lkj546'
      MYSQL_ROOT_PASSWORD: lejwelfkjhFjkhwefkjwejwF
    volumes:
      - mysql_data:/var/lib/mysql-files
      - mysql_config:/etc/mysql
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        constraints:
          - "node.role==worker"
