version: '3.6'

volumes:
  registry_data:

networks:
  svc_net:
    name: "service_network"
    driver: overlay

services:
  registry:
    image: registry
    hostname: registry
    networks:
      - svc_net
    volumes:
      - registry_data:/var/lib/registry
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"


